// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoTVbYpK7ZAw1V79FbXPtYtIow21kbPWw',
    appId: '1:1062950275105:web:7b2fcb5c091b3b442fbb60',
    messagingSenderId: '1062950275105',
    projectId: 'hoteldb-2a0f5',
    authDomain: 'hoteldb-2a0f5.firebaseapp.com',
    storageBucket: 'hoteldb-2a0f5.firebasestorage.app',
    measurementId: 'G-8704BB763T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEPIHaWe8z5NasMGg5vLw3diPxsapVDV4',
    appId: '1:1062950275105:android:1e70b0c742a4a8ed2fbb60',
    messagingSenderId: '1062950275105',
    projectId: 'hoteldb-2a0f5',
    storageBucket: 'hoteldb-2a0f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCez2T6RY8JnQ4AcuecBSmgg2T-RpVARco',
    appId: '1:1062950275105:ios:35696e8793ff0b122fbb60',
    messagingSenderId: '1062950275105',
    projectId: 'hoteldb-2a0f5',
    storageBucket: 'hoteldb-2a0f5.firebasestorage.app',
    iosBundleId: 'com.example.hotel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCez2T6RY8JnQ4AcuecBSmgg2T-RpVARco',
    appId: '1:1062950275105:ios:35696e8793ff0b122fbb60',
    messagingSenderId: '1062950275105',
    projectId: 'hoteldb-2a0f5',
    storageBucket: 'hoteldb-2a0f5.firebasestorage.app',
    iosBundleId: 'com.example.hotel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoTVbYpK7ZAw1V79FbXPtYtIow21kbPWw',
    appId: '1:1062950275105:web:10d654404a52fb672fbb60',
    messagingSenderId: '1062950275105',
    projectId: 'hoteldb-2a0f5',
    authDomain: 'hoteldb-2a0f5.firebaseapp.com',
    storageBucket: 'hoteldb-2a0f5.firebasestorage.app',
    measurementId: 'G-DF7Y5Z7BFB',
  );
}
